### ISSUE TITLE
MVP 1

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#1]
As a Dataset Creator I want to drop a file in and have a tabular data resource generated so that I can use it in other frictionless tools or save in a backend

### Remarks

* Build in a reusable way: reuse UI and library components
  * data.js - https://github.com/datahq/data.js
  * goodtables-js - atm there is some basic validation in tableschema-js
* Build in a well documented way ... so that someone else could build their own custom importer using this

### Acceptance criteria

* [ ] I can add a CSV and get a valid tabular data resource at the end (or tabular data package ...)

### Tasks

* [x] Scaffold project #2 
* [x] Mock start and end screen #3 
* [x] Working file upload #4 
* [x] Raw Preview page #5 
* [x] Schema editor page #6 

#### Later - bonus items

* [x] Preview includes structural validation
  * [x] requires goodtables-js port of structural validation
* [ ] Support xlsx files

**Comment by acouch** [comment]
Finishing this is blocked by https://github.com/datopian/data.js/issues/49 . I might just skip the data.js integration if we can't figure that one out.
