### ISSUE TITLE
Scaffold project for MVP

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#2]
Project is scaffolded and has a skeleton.

### Acceptance criteria

* [x] I can visit the site at datopian.github.io/import-ui/

### Tasks

* [x] Add license (MIT)
* [x] Set up with webpack (or similar) - we are using react and ES6 style stuff
* [x] index.html shell
* [x] Basic developer instructions
* [x] Deployment to gh-pages

**Comment by acouch** [comment]
Started this here: #7

**Comment by acouch** [comment]
PR #7 fulfills the above criteria.

**Comment by acouch** [comment]
This has been accomplished.
