### ISSUE TITLE
Mock start and end screen

### ISSUE THREAD

**Issue by acouch** [datopian/import-ui#3]
Start and end screen are mocked out and visible.

### Acceptance criteria

- [x] I can visit the start page and see a place to drop a file
- [x] I can drop a file into the page (though nothing happens)
- [x] I can click through to the publish screen
- [x] I can navigate back to the File load screen using breadcrumbs

### Tasks

* [x] Mock Screen 1: File load
* [x] Mock Screen 5: Publish screen
* [x] (?) Move between the screens (even though no file there - just do it via the url)
* [x] Breadcrumbs / breadcrumb url hashes

## File Upload mockup
See: 
![image](https://user-images.githubusercontent.com/512243/52427542-21c99780-2ace-11e9-9083-8d8067446743.png)

## Publish mockup
![image](https://user-images.githubusercontent.com/512243/52427676-67866000-2ace-11e9-85a4-fbee24cce05e.png)

*Nothing need work at this point e.g. file load does nothing -- just an `<input type="file">`*

**Comment by acouch** [comment]
I've got the basic routing down here: https://github.com/datopian/import-ui/tree/issue-3-mock-screen

Using react router and context to keep the state and click through the screens.

**Comment by acouch** [comment]
Ready for review: #8
