### ISSUE TITLE
Working file upload

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#4]
File upload actually works ... (very simple - don't use a lib)

### Acceptance criteria

* [x] I can drop select / drop a CSV on there and it works and takes me to next screen 

Bonus

* [x] If i drop a non CSV file on there it tells me it doesn't work

### Tasks

* [x] File input working (simplest possible)
* [x] just store in the browser (assume it is small)
* [x] Go to next screen (even if last one atm)

Bonus:

* [x] (validate it is a file we can handle ) extract file type (data.js does this for you) and you check it is csv and report an error if not csv

**Comment by acouch** [comment]
I've completed this.

**Comment by rufuspollock** [comment]
@acouch is there an example link so you can use a sample file to try it out (does it work with urls as well as local files?)

**Comment by acouch** [comment]
Yep. Let me know if there is a file you like or I'll just chose one from our examples.

**Comment by acouch** [comment]
Added! :)

![image](https://user-images.githubusercontent.com/512243/52905986-0dde0e00-3211-11e9-9007-7af4892c4c19.png)
