### ISSUE TITLE
Preview working (no validation)

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#5]
The raw preview screen (UI.2) is working

### Acceptance criteria

* [x] I can see the data in the file in rows and columns for first 10 columns
* [x] I can click through

Bonus

* [x] show first 4 rows, last 4 rows and random rows (...)
* [x] Show total number of rows
* [x] Show file size (?)

### Tasks

* [x] File title (and file name) box
* [ ] parse loaded file with data.js
  * [ ] May need to browserify data.js and check how this works with file data in the browser
* [x] display in a table (react-table or similar)
* [x] Next button to take you to next screen

**Comment by acouch** [comment]
I've started this.

**Comment by acouch** [comment]
Finishing this is blocked by datopian/data.js#49 . I might just skip the data.js integration if we can't figure that one out.
