### ISSUE TITLE
Schema editor

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#6]
Edit the table schema metadata alongside preview of the data

### Acceptance

* [x] Initial data preview visible to user
* [x] Ability to edit "type" in row above first row
* [x] Ability to see validation results
* [x] Can click "next" to get to "Final" screen

### Tasks

Using a data.js File object ... 

* [ ] header shown (bolded ...)
* [x] table schema metadata editor (type only)
  * [x] display
  * [x] editable
* [x] data preview (clearly different from metadata)
  * [x] live updating with validation results
    * [ ] TODO: factor out tableschema-js validator into a goodtables-js library

Bonus - probably later

* [ ] Swap to vertical view (if a lot of columns) - probably toggle option
* [x] Description and Format options in table schema editor

**Comment by acouch** [comment]
I've got this working in that there is live validation for the data types:

![image](https://user-images.githubusercontent.com/512243/53695053-e9dc0a00-3d84-11e9-8aa3-ea4b49545540.png)


I have some basic validation that could be expanded and probably added to goodtables: https://github.com/datopian/import-ui/blob/schema-edit/src/context/validate.js#L23

```javascript

function validateItem(item, type) {
  switch(type) {
    case "string":
      if (!isString(item)) {
        if (!isString(castString("", item))) {
          return false;
        }
      }
      break;
    case "integer":
      if (!isInteger(item)) {
        item = castInteger("", item);
        if (!isInteger(castInteger("", item))) {
          return false;
        }
}
```
