### ISSUE TITLE
Publish screen shows datapackage.json on publish

### ISSUE THREAD

**Issue by rufuspollock** [datopian/import-ui#9]
As a Curator I want to see the resulting datapackage.json (plus maybe some instructions of how this would wire up - maybe a link to README for code) so that I have a sense of how this works and i can download the datapackage.json

## Acceptance criteria

* [ ] The datapackage.json is shown pretty-printed in textarea or similar
* [ ] I can copy it to a clipboard in one click (a la google translate)
* [ ] Link to github readme on how to wire this up

## Tasks

* [ ] ...
